# Generated by Django 5.2.18 on 2026-10-09 21:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('running', 'Running'), ('success', 'Success'), ('failed', 'Failed')], max_length=20)),
                ('snapshot_id', models.CharField(blank=True, max_length=100)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, max_length=5000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_filename', models.CharField(max_length=255)),
                ('original_key', models.CharField(max_length=255, unique=True)),
                ('thumbnail_key', models.CharField(blank=True, max_length=255)),
                ('preview_key', models.CharField(blank=True, max_length=255)),
                ('sha256', models.CharField(db_index=True, max_length=64)),
                ('byte_size', models.PositiveBigIntegerField()),
                ('mime_type', models.CharField(max_length=80)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('taken_at', models.DateTimeField(blank=True, null=True)),
                ('taken_local', models.CharField(blank=True, max_length=32)),
                ('taken_offset_minutes', models.SmallIntegerField(blank=True, null=True)),
                ('display_date', models.DateField(db_index=True)),
                ('date_source', models.CharField(choices=[('exif', 'EXIF'), ('file', 'Trusted import file date'), ('upload', 'Upload time'), ('manual', 'Manually edited')], max_length=10)),
                ('exif_date_raw', models.CharField(blank=True, max_length=100)),
                ('caption', models.TextField(blank=True, max_length=5000)),
                ('width', models.PositiveIntegerField(blank=True, null=True)),
                ('height', models.PositiveIntegerField(blank=True, null=True)),
                ('orientation', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('camera_make', models.CharField(blank=True, max_length=150)),
                ('camera_model', models.CharField(blank=True, max_length=150)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('location_label', models.CharField(blank=True, max_length=250)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('ready', 'Ready'), ('failed', 'Failed')], default='pending', max_length=12)),
                ('trashed_at', models.DateTimeField(blank=True, null=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='memories.photo')),
            ],
        ),
        migrations.CreateModel(
            name='AlbumPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(default=0)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memories.album')),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memories.photo')),
            ],
        ),
        migrations.AddField(
            model_name='album',
            name='cover_photo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cover_for', to='memories.photo'),
        ),
        migrations.AddField(
            model_name='album',
            name='photos',
            field=models.ManyToManyField(related_name='albums', through='memories.AlbumPhoto', to='memories.photo'),
        ),
        migrations.CreateModel(
            name='ProcessingJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('available_at', models.DateTimeField()),
                ('lease_until', models.DateTimeField(blank=True, null=True)),
                ('error_code', models.CharField(blank=True, max_length=80)),
                ('photo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='memories.photo')),
            ],
        ),
        migrations.AddIndex(
            model_name='photo',
            index=models.Index(condition=models.Q(('status', 'ready'), ('trashed_at__isnull', True)), fields=['-display_date', '-id'], name='photo_visible_date'),
        ),
        migrations.AddIndex(
            model_name='photo',
            index=models.Index(fields=['-uploaded_at'], name='memories_ph_uploade_9bed08_idx'),
        ),
        migrations.AddConstraint(
            model_name='photo',
            constraint=models.CheckConstraint(condition=models.Q(('latitude__isnull', True), models.Q(('latitude__gte', -90), ('latitude__lte', 90)), _connector='OR'), name='valid_latitude'),
        ),
        migrations.AddConstraint(
            model_name='photo',
            constraint=models.CheckConstraint(condition=models.Q(('longitude__isnull', True), models.Q(('longitude__gte', -180), ('longitude__lte', 180)), _connector='OR'), name='valid_longitude'),
        ),
        migrations.AddConstraint(
            model_name='photo',
            constraint=models.CheckConstraint(condition=models.Q(('orientation__isnull', True), models.Q(('orientation__gte', 1), ('orientation__lte', 8)), _connector='OR'), name='valid_orientation'),
        ),
        migrations.AddConstraint(
            model_name='favorite',
            constraint=models.UniqueConstraint(fields=('user', 'photo'), name='unique_user_favorite'),
        ),
        migrations.AddIndex(
            model_name='albumphoto',
            index=models.Index(fields=['album', 'position'], name='memories_al_album_i_75da82_idx'),
        ),
        migrations.AddConstraint(
            model_name='albumphoto',
            constraint=models.UniqueConstraint(fields=('album', 'photo'), name='unique_album_photo'),
        ),
        migrations.AddIndex(
            model_name='processingjob',
            index=models.Index(fields=['available_at', 'lease_until'], name='memories_pr_availab_176655_idx'),
        ),
    ]
